files: ^src/
repos:
-   repo: https://github.com/standard/standard
    rev: v17.1.0
    hooks:
      - id: standard
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ['--enforce-all', '--maxkb', '200']
    -   id: trailing-whitespace
    -   id: check-yaml
        args: ['--unsafe']
    -   id: check-toml
    -   id: check-merge-conflict
